shop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = "adminapp"

urlpatterns = [
    path("users/create/", adminapp.UserCreateView.as_view(), name="create_user"),
    path("users/read/", adminapp.UserListView.as_view(), name="users"),
    path("users/update/<int:pk>/", adminapp.UserUpdateView.as_view(), name="update_user"),
    path("users/delete/<int:pk>/", adminapp.UserDeleteView.as_view(), name="delete_user"),
    path(
        "categories/create/",
        adminapp.create_category,
        name="create_category",
    ),
    path("categories/read/", adminapp.categories, name="categories"),
    path(
        "categories/update/<int:pk>/",
        adminapp.update_category,
        name="update_category",
    ),
    path(
        "categories/delete/<int:pk>/",
        adminapp.delete_category,
        name="delete_category",
    ),
    path(
        "products/create/category/<int:pk>/",
        adminapp.ProductCreateView.as_view(),
        name="create_product",
    ),
    path("products/read/category/<int:pk>/", adminapp.ProductListView.as_view(), name="products"),
    path("products/read/<int:pk>/", adminapp.ProductView.as_view(), name="read_product"),
    path(
        "products/update/<int:pk>/",
        adminapp.ProductUpdateView.as_view(),
        name="update_product",
    ),
    path(
        "products/delete/<int:pk>/",
        adminapp.delete_product,
        name="delete_product",
    ),
]

shop/shop/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include

from mainapp import views as mainapp


urlpatterns = [
    path("", include("social_django.urls", namespace="social")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("adminapp/", include("adminapp.urls", namespace="custom_admin")),
    path("", mainapp.index, name="index"),
    path("contact/", mainapp.contact, name="contact"),
    path("product/", include("mainapp.urls", namespace="product")),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("cart/", include("cartapp.urls", namespace="cart")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/adminapp/models.py
from django.db import models

# Create your models here.

shop/adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm, ShopUserRegisterForm
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = "__all__"


class ShopUserAdminCreateForm(ShopUserRegisterForm):
    class Meta:
        model = ShopUser
        fields = (
            "username",
            "first_name",
            "password",
            "email",
            "age",
            "city",
            "phone",
            "image",
        )


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

shop/adminapp/views/category_views.py
from mainapp.models import Product, ProductCategory
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test
from adminapp.forms import ProductCategoryEditForm
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    categories_list = ProductCategory.objects.all()

    return render(
        request,
        "adminapp/category/categories.html",
        context={
            "title": "Admin/categories",
            "categories": categories_list,
        },
    )


@user_passes_test(lambda u: u.is_superuser)
def create_category(request):
    if request.method == "POST":
        category_form = ProductCategoryEditForm(request.POST, request.FILES)
        if category_form.is_valid():
            category_form.save()
            return HttpResponseRedirect(reverse("adminapp:categories"))
    else:
        category_form = ProductCategoryEditForm()

    return render(
        request,
        "adminapp/category/update_category.html",
        context={
            "title": "Admin/category/create",
            "update_form": category_form,
        },
    )


@user_passes_test(lambda u: u.is_superuser)
def update_category(request, pk):
    edit_category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == "POST":
        edit_form = ProductCategoryEditForm(request.POST, request.FILES, instance=edit_category)

        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse("adminapp:update_category", args=[edit_category.pk]))
    else:
        edit_form = ProductCategoryEditForm(instance=edit_category)

    return render(
        request,
        "adminapp/category/update_category.html",
        context={"title": "Admin/category/edit", "update_form": edit_form},
    )


@user_passes_test(lambda u: u.is_superuser)
def delete_category(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == "POST":
        category.is_active = False
        category.save()
        return HttpResponseRedirect(reverse("adminapp:categories"))

    return render(
        request,
        "adminapp/category/delete_category.html",
        context={
            "title": "Admin/category/delete",
            "category_to_delete": category,
        },
    )

shop/adminapp/views/product_views.py
import pdb
from mainapp.models import Product, ProductCategory
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView
from django.utils.decorators import method_decorator
from adminapp.forms import ProductEditForm


class ProductCreateView(CreateView):
    model = Product
    template_name = "adminapp/product/update_product.html"
    fields = (
        "category",
        "name",
        "price",
        "color",
        "description",
        "image",
        "quantity",
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.get_category()
        return context

    def get_initial(self):
        return {"category": self.get_category()}

    def get_category(self):
        return ProductCategory.objects.get(pk=self.kwargs["pk"])

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductListView(ListView):
    model = Product
    template_name = "adminapp/product/products.html"

    def get_category(self):
        return ProductCategory.objects.get(pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.get_category()
        return context

    def get_queryset(self):
        return self.model.objects.filter(category__pk=self.kwargs["pk"])

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductView(DetailView):
    model = Product
    template_name = "adminapp/product/read_product.html"


class ProductUpdateView(UpdateView):
    model = Product
    fields = "__all__"
    template_name = "adminapp/product/update_product.html"

    def get_success_url(self):
        return reverse_lazy("adminapp:products", args=[self.object.category.pk])


@user_passes_test(lambda u: u.is_superuser)
def create_product(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == "POST":
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse_lazy("adminapp:products", args=[pk]))
    else:
        product_form = ProductEditForm(initial={"category": category})

    return render(
        request,
        "adminapp/product/update_product.html",
        context={
            "title": "Admin/create",
            "update_form": product_form,
            "category": category,
        },
    )


@user_passes_test(lambda u: u.is_superuser)
def read_product(request, pk):
    product = get_object_or_404(Product, pk=pk)

    return render(
        request,
        "adminapp/product/read_product.html",
        context={
            "title": f"Admin/{product.name}/read",
            "product": product,
        },
    )


@user_passes_test(lambda u: u.is_superuser)
def update_product(request, pk):
    edit_product = get_object_or_404(Product, pk=pk)

    if request.method == "POST":
        edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)

        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse_lazy("adminapp:update_product", args=[edit_product.pk]))

    else:
        edit_form = ProductEditForm(instance=edit_product)

    return render(
        request,
        "adminapp/product/update_product.html",
        context={
            "title": f"Admin/{edit_product.name}/edit",
            "update_form": edit_form,
            "category": edit_product.category,
        },
    )


@user_passes_test(lambda u: u.is_superuser)
def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse_lazy("adminapp:products", args=[product.category.pk]))

    return render(
        request,
        "adminapp/product/delete_product.html",
        context={
            "title": f"Admin/{product.name}/delete",
            "product_to_delete": product,
            "category": product.category,
        },
    )

shop/adminapp/views/user_views.py
from django.shortcuts import HttpResponseRedirect
from authapp.models import ShopUser
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.utils.decorators import method_decorator

from adminapp.forms import ShopUserAdminEditForm, ShopUserAdminCreateForm


class UserListView(ListView):
    model = ShopUser
    template_name = "adminapp/user/users.html"

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class UserCreateView(CreateView):
    model = ShopUser
    template_name = "adminapp/user/update_user.html"
    form_class = ShopUserAdminCreateForm
    success_url = reverse_lazy("adminapp:users")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Admin/create"
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class UserUpdateView(UpdateView):
    model = ShopUser
    template_name = "adminapp/user/update_user.html"
    form_class = ShopUserAdminEditForm
    success_url = reverse_lazy("adminapp:users")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_name = self.object.username
        context["title"] = f"Admin/{user_name}/edit"
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = "adminapp/user/delete_user.html"
    success_url = reverse_lazy("adminapp:users")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

shop/adminapp/templates/adminapp/product/delete_product.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="admin_delete">
    Are you sure you want to delete <b>{{ product_to_delete.name }} </b>?
    <form action="{% url 'adminapp:delete_product' product_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="admin_button delete" type="submit" value="Delete">
    </form>
    <button class="admin_button cancel">
      <a href="{% url 'adminapp:products' category.pk %}">
        Cancel
      </a>
    </button>
  </div>
{% endblock %}

shop/adminapp/templates/adminapp/product/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="admin_list product_list">
    <button class="admin_button">
      <a href="{% url 'adminapp:create_product' category.pk %}">
        New product
      </a>
    </button>
		
    {% for product in object_list %}
      <div class="product_record">
        <img 
          src="/media/{{product.image|default:'images/default.png'}}"
          alt="{{ product.name }}"
          class="admin_product_img">
        <div class="product_name">
          {{ product.name|title }}
        </div>
        <div class="product_actions">
          <button class="admin_button">
            <a href="{% url 'adminapp:read_product' product.pk %}">
              Details
            </a>
          </button>
          <button class="admin_button">
            <a href="{% url 'adminapp:update_product' product.pk %}">
              Edit
            </a>
          </button>
          <button class="admin_button">
            <a href="{% url 'adminapp:delete_product' product.pk %}">
              Delete
            </a>
          </button>
        </div>
        <div class="summary">
          <p><b>Price: </b>{{ product.price }}</p>
          <p><b>Quantity: </b>{{ product.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ product.description|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

shop/adminapp/templates/adminapp/product/read_product.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <div class="product_read">
    <div class="product_name">
      Продукт<strong>{{ product.category.name|title }} / 
                     {{ product.name|title }}</strong> 
    </div>
    <img src="/media/{{ product.image|default:'images/default.jpg' }}"
         alt="{{ product.name }}">
    <div class="summary">
      <b>Price: </b>
      <p>{{ product.price }}</p>
      <b>Quantity: </b>
      <p>{{ product.quantity }}</p>
      <b>In stock: </b>
      <p>{% if product.is_active %}Yes{% else %}No{% endif %}</p>
      <p>
        <button>
          <a href={% url 'adminapp:update_product' product.pk %}>
            Edit
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href={% url 'adminapp:delete_product' product.pk %}>
            Delete
          </a>
        </button>
      </p>
      <p>
        <button>
          <a href={% url 'adminapp:products' product.category.pk %}>
            Back
          </a>
        </button>
      </p>
    </div>
    <div class="product_desc">
      <b>Description: </b>
      <p>{{ product.description }}</p>
    </div>
  </div>
{% endblock %}

shop/adminapp/templates/adminapp/product/update_product.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="Save">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'adminapp:products' product.category.pk %}">
      To products list
    </a>
  </button>
{% endblock %}