shop/cartapp/urls.py
from django.urls import path
from . import views as cartapp


app_name = "cartapp"

urlpatterns = [
    path("", cartapp.cart_view, name="cart"),
    path("add/<int:product_id>/", cartapp.add_item, name="add"),
    path("remove/<int:cart_item_id>/", cartapp.remove_item, name="remove"),
    path(
        "edit/<int:cart_item_id>/<int:quantity>/",
        cartapp.edit_item,
        name="edit",
    ),
]

shop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp


app_name = "mainapp"

urlpatterns = [
    path("", mainapp.product, name="index"),
    path("<int:pk>/", mainapp.product, name="category"),
    path("<int:pk>/page/<int:page>/", mainapp.product, name="page"),
    path("product/<int:pk>/", mainapp.product_page, name="product"),
]

shop/shop/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include

from mainapp import views as mainapp


urlpatterns = [
    path("", include("social_django.urls", namespace="social")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("adminapp/", include("adminapp.urls", namespace="custom_admin")),
    path("", mainapp.index, name="index"),
    path("contact/", mainapp.contact, name="contact"),
    path("product/", include("mainapp.urls", namespace="product")),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("cart/", include("cartapp.urls", namespace="cart")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/mainapp/models.py
from functools import cache, lru_cache
from django.db import models
import random


class ProductCategory(models.Model):
    """Model of category for Product model."""

    name = models.CharField(verbose_name="Category name", max_length=100)
    description = models.TextField(
        verbose_name="Category description", blank=True
    )
    is_active = models.BooleanField(verbose_name="Is active", default=True)

    class Meta:
        verbose_name_plural = "Product categories"

    def __str__(self):
        return self.name


class ProductManager(models.Manager):
    @property
    def active_items(self):
        return Product.objects.filter(is_active=True)


class Product(models.Model):
    """Model of shop product."""

    category = models.ForeignKey(
        ProductCategory, on_delete=models.CASCADE, blank=True
    )
    name = models.CharField(verbose_name="Product name", max_length=120)
    price = models.DecimalField(
        verbose_name="Product price", max_digits=6, decimal_places=2, default=0
    )
    color = models.PositiveIntegerField(
        verbose_name="Product color", default=0x000000
    )
    description = models.TextField(
        verbose_name="Product description", blank=True
    )
    image = models.ImageField(
        verbose_name="Product image", blank=True, upload_to="products"
    )
    quantity = models.PositiveIntegerField(
        verbose_name="Product quantity", default=0
    )

    is_active = models.BooleanField(verbose_name="Is active", default=True)

    objects = ProductManager()

    def __str__(self):
        return self.name
    
    @staticmethod
    def random_product(query):
        """Returns random product from pool."""
        return random.choice(query)

shop/adminapp/views/product_views.py
import pdb
from mainapp.models import Product, ProductCategory
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView
from django.utils.decorators import method_decorator
from adminapp.forms import ProductEditForm


class ProductCreateView(CreateView):
    model = Product
    template_name = "adminapp/product/update_product.html"
    fields = (
        "category",
        "name",
        "price",
        "color",
        "description",
        "image",
        "quantity",
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.get_category()
        return context

    def get_initial(self):
        return {"category": self.get_category()}

    def get_category(self):
        return ProductCategory.objects.get(pk=self.kwargs["pk"])

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductListView(ListView):
    model = Product
    template_name = "adminapp/product/products.html"

    def get_category(self):
        return ProductCategory.objects.get(pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.get_category()
        return context

    def get_queryset(self):
        return self.model.objects.filter(category__pk=self.kwargs["pk"])

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ProductView(DetailView):
    model = Product
    template_name = "adminapp/product/read_product.html"


class ProductUpdateView(UpdateView):
    model = Product
    fields = "__all__"
    template_name = "adminapp/product/update_product.html"

    def get_success_url(self):
        return reverse_lazy("adminapp:products", args=[self.object.category.pk])


@user_passes_test(lambda u: u.is_superuser)
def create_product(request, pk):
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == "POST":
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse_lazy("adminapp:products", args=[pk]))
    else:
        product_form = ProductEditForm(initial={"category": category})

    return render(
        request,
        "adminapp/product/update_product.html",
        context={
            "title": "Admin/create",
            "update_form": product_form,
            "category": category,
        },
    )


@user_passes_test(lambda u: u.is_superuser)
def read_product(request, pk):
    product = get_object_or_404(Product, pk=pk)

    return render(
        request,
        "adminapp/product/read_product.html",
        context={
            "title": f"Admin/{product.name}/read",
            "product": product,
        },
    )


@user_passes_test(lambda u: u.is_superuser)
def update_product(request, pk):
    edit_product = get_object_or_404(Product, pk=pk)

    if request.method == "POST":
        edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)

        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse_lazy("adminapp:update_product", args=[edit_product.pk]))

    else:
        edit_form = ProductEditForm(instance=edit_product)

    return render(
        request,
        "adminapp/product/update_product.html",
        context={
            "title": f"Admin/{edit_product.name}/edit",
            "update_form": edit_form,
            "category": edit_product.category,
        },
    )


@user_passes_test(lambda u: u.is_superuser)
def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == "POST":
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse_lazy("adminapp:products", args=[product.category.pk]))

    return render(
        request,
        "adminapp/product/delete_product.html",
        context={
            "title": f"Admin/{product.name}/delete",
            "product_to_delete": product,
            "category": product.category,
        },
    )

shop/mainapp/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.cache import cache
from django.views.decorators.cache import cache_page

from functools import lru_cache

from cartapp.models import Cart
from .models import Product, ProductCategory


@lru_cache
def get_product(category="all"):
    if category == "all":
        return Product.objects.all()[:4]
    return Product.objects.filter(category_id=category)


def get_category(pk=None):
    if settings.LOW_CACHE:
        if pk:
            KEY = f"category_{pk}"
            category = cache.get(KEY)
            if not category:
                category = ProductCategory.objects.filter(pk=pk)
                cache.set(KEY, category)
            return category
        KEY = "all_categories"
        categories = cache.get(KEY)
        if not categories:
            categories = ProductCategory.objects.all()
            cache.set(KEY, categories)
        return categories
    return ProductCategory.objects.filter(pk=pk) if pk else \
            ProductCategory.objects.all()

def index(request):
    """View for main page."""
    product = get_product()
    return render(
        request,
        "mainapp/index.html",
        context={
            "title": "Main",
            "products": product,
        },
    )


def product(request, pk=None, page=1):
    """View for products page."""
    products = get_product(pk) if pk else Product.objects.all()
    hot_product = Product.random_product(products)
    categories = get_category()

    if pk is not None:
        if pk == 0:
            category = {
                "pk": 0,
                "name": "all",
            }
            products = Product.objects.filter(is_active=True)
        else:
            category = get_category(pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True)

    paginator = Paginator(products, 4)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    try:
        content = {
            "title": "Products",
            "products": products_paginator,
            "categories": categories,
            "category": category,
            "hot_product": hot_product,
        }

    except UnboundLocalError:
        content = {
            "title": "Products",
            "products": products_paginator,
            "categories": categories,
            "category": {
                "pk": 0,
                "name": "all",
            },
            "hot_product": hot_product,
        }

    return render(request, "mainapp/products.html", context=content)


def product_page(request, pk):
    """View for specific product."""
    title = "Product page"
    product = get_object_or_404(Product, pk=pk)
    try:
        cart = Cart.get_cart(user=request.user)
    except TypeError:
        return HttpResponseRedirect(reverse("authapp:login"))

    return render(
        request,
        "mainapp/product_page.html",
        context={
            "title": title,
            "product": product,
            "cart": cart,
        },
    )


def category(request, pk):
    """View for page products, used for display specific category of product"""
    categories = get_category()
    category = get_category(pk=pk)
    products = Product.objects.filter(category=category)
    hot_product = Product.random_product(Product.objects.filter(category=category))

    return render(
        request,
        "mainapp/products.html",
        context={
            "title": "Products",
            "products": products,
            "categories": categories,
            "hot_product": hot_product,
        },
    )


def contact(request):
    """View for contacts page."""
    return render(
        request,
        "mainapp/contact.html",
        context={
            "title": "Contacts",
        },
    )

shop/mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{{ title }}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
	{% block js %}
	<script src="{% static 'scripts/bootstrap.min.js' %}"></script>
	<script src="{% static 'scripts/jquery-3.6.0.js' %}"></script>
	{% endblock js %}
</head>
<body>
	<div class="container">
		
		{% block content %}
		{% endblock content %}
		
	</div>
	
	{% include  "mainapp/includes/inc_footer.html" %}
	<script type="text/javascript">
		var dropdown = document.getElementById("dropdown");
		var dropdown_menu = dropdown.nextElementSibling;
		dropdown.addEventListener("mouseover", function() {
			dropdown_menu.style.display = "block";
		})
		dropdown.addEventListener("mouseout", function() {
			if (!dropdown_menu.matches(":hover")) {
				dropdown_menu.style.display = "none";
			}
		})
		dropdown_menu.addEventListener("mouseleave", function (event) {
			event.target.style.display = "none";
		})
	</script>
	
</body>
</html>

shop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load cache %}
{% load static %}
{% block content %}
{% cache 3600 contact_page_content %}
<div class="hero">
	
	{% include 'mainapp/includes/inc_menu.html' %}
	
	<h1>наши контакты</h1>
</div>

<div class="location">
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
	<div class="location-1">
		<i class="fa fa-map-marker fa-5x"></i>
		<h4>Москва</h4>
		<div class="contacts">
			<h5>Телефон</h5>
			<p>+7-888-888-8888</p>
		</div>
		<div class="contacts">
			<h5>Email</h5>
			<p>info@geekshop.ru</p>
		</div>
		<div class="contacts">
			<h5>Адрес</h5>
			<p>В пределах МКАД</p>
		</div>
	</div>
</div>

<div class="clr"></div>
{% endcache %}
{% endblock content %}	

{% include 'mainapp/includes/inc_footer.html' %}	

</body>
</html>

shop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="slider">
	
	{% include 'mainapp/includes/inc_menu.html' %}
	
	<div class="text-slider">
		<h3 class="green">тенденции</h3>
		<h3 class="big"> удобные стулья</h3>
		<p>Новый уровень комфорта. Отличные характеристики.</p>
		<a href="#" class="button-order">заказать <img src="{% static '/img/arrow.png' %}" alt=""></a>
	</div>	
	<div class="navi">
		<a href="#"></a><a href="#"></a><a href="#"></a>
	</div>
</div>

<div class="featured">
	<div class="featured-menu">
		<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
	</div>
	<a class="explore" href="#">показать все <img src="{% static '/img/arrow.png'%}" alt=""></a>
	<div class="clearfix">
	</div>
	<div class="tab-content">
		
		{% include 'mainapp/includes/inc_related_products.html' %}
		
	</div>
</div>

<div class="clr"></div>

{% endblock content %}

{% include  "mainapp/includes/inc_footer.html" %}


</body>
</html>

shop/mainapp/templates/mainapp/product_page.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block js %}
  
  <script src="{% static 'scripts/cart_scripts.js'%}"></script>
  <script type="text/javascript">
    window.onload = function () {
      var quantity = {{ product.quantity }};
      if (quantity - 1 < 0) {
        var buy_button = document.getElementsByClassName("red-button")[0];
        buy_button.style.pointerEvents = "none";
        buy_button.style.opacity = "0.5";
        buy_button.text = "Sorry, out of stock";
      }
    }
  </script>
{% endblock js %}

{% block content %}
<div class="hero-white">
  
  {% include 'mainapp/includes/inc_menu.html' %}
  
</div>
<div class="details-products">
  <div class="details-slider">
    <div class="slider-product">
      <img src="{{ product.image.url }}" 
      alt="{{ product.description }}"
      class="slider_product_main">
    </div>
    <div class="slider-control">
      <div class="block">
        <a href="#">
          <img src="{{ product.image.url }}"
          alt="вариант 1"
          class="slider_tiny">
        </a>
      </div>
      <div class="block">
        <a href="#">
          <img src="{{ product.image.url }}"
          alt="вариант 2"
          class="slider_tiny">
        </a>
      </div>
      <div class="block">
        <a href="#">
          <img src="{{ product.image.url }}"
          alt="вариант 3"
          class="slider_tiny">
        </a>
      </div>
    </div>
  </div>
  
  <div class="description">
    <h3 class="big-bold">{{ product.name }}</h3>
    <br>
    <p class="price"> {{ product.price }}</p>
    <a href="{% url 'cart:add' product.pk %}" class="red-button">
      Add to cart 
      <i class="fa fa-chevron-right" aria-hidden="true"></i>
    </a>
    <div class="description-text">
      {{ product.description }}
    </div>
  </div>
</div>

</div>


{% endblock content %}
<div class="clearfix"></div>

shop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="hero-white">
	
	{% include 'mainapp/includes/inc_menu.html' %}
	
</div>

<div class="details">
	<div class="links clearfix">
		<ul class="links-menu">
			<li><a href="{% url 'product:index' %}"
				{% if request.resolver_match.view_name == 'product:index' %} class="active" 
				{% endif %}>all</a></li>
				{% for category in categories %}
				<li><a href="{% url 'product:category' category.pk %}" 
					{% if request.resolver_match.kwargs.pk == category.pk %}
					class='active'
					{% endif %}>{{ category.name }}
				</a></li>
				{% endfor %}
			</ul>
	</div>
		
	{% include 'mainapp/includes/inc_hot_product.html'%}
	
	<div class="products_list">
		<div class="clearfix">
			<h2>Category: {{ category.name }}</h2>
			<div class="paginator">
				{% if products.has_previous %}
					<a href="{% url 'product:page' category.pk products.previous_page_number %}">
					&larr;
					</a>
				{% endif %}
				<span class="current">
					Page {{ products.number }} of 
					{{ products.paginator.num_pages }}
				</span>
				{% if products.has_next %}
					<a href="{% url 'product:page' category.pk products.next_page_number %}">
					&rarr;
					</a>
				{% endif %}
			</div>
		</div>
	</div>
	<div class="related">
		<div class="title clearfix">
			<h2>Related products</h2>
			<a class="explore" href="#">Show all <img src="{% static 'img/arrow.png' %}" alt=""></a>
		</div>
		<div class="related products">
			{% include 'mainapp/includes/inc_related_products.html' %}
		</div>
	</div>
</div>
	
	
<div class="clr"></div>
	
{% endblock content%}	
	
</body>
</html>