shop/authapp/urls.py
from django.urls import path, re_path
from . import views as authapp


app_name = "authapp"

urlpatterns = [
    path("login/", authapp.login, name="login"),
    path("logout/", authapp.logout, name="logout"),
    path("registration/", authapp.registration, name="registration"),
    path("edit/", authapp.edit, name="edit"),
    re_path(r"^verify/(?P<email>.+)/(?P<activation_key>\w+)", authapp.verify, name="verify"),
]

shop/shop/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include

from mainapp import views as mainapp


urlpatterns = [
    path("", include("social_django.urls", namespace="social")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("adminapp/", include("adminapp.urls", namespace="custom_admin")),
    path("", mainapp.index, name="index"),
    path("contact/", mainapp.contact, name="contact"),
    path("product/", include("mainapp.urls", namespace="product")),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("cart/", include("cartapp.urls", namespace="cart")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.forms import ValidationError
from django.utils.timezone import now

from datetime import timedelta
from django.db.models.signals import post_save
from django.dispatch import receiver


def get_expiration_time():
    return now() + timedelta(hours=48)


class ShopUser(AbstractUser):
    age = models.PositiveIntegerField(verbose_name="Age", default=18)
    image = models.ImageField(verbose_name="User image", blank=True, upload_to="users")
    phone = models.CharField(
        verbose_name="Phone number",
        max_length=20,
        blank=True,
        validators=[
            RegexValidator(
                r"\d-\d{3}-\d{3}-\d{4}$",
                message="Phone must be in *-***-***-**** format.",
            )
        ],
    )
    city = models.CharField(verbose_name="City", max_length=30, blank=True)
    activation_key = models.CharField(max_length=128, blank=True)
    key_expires = models.DateTimeField(default=get_expiration_time)

    def clean(self):
        if self.age > 100:
            raise ValidationError(
                {
                    "age": f"Seriosly, age {self.age}?\
                    Must be under 100, or i don't pass you."
                }
            )


class ShopUserProfile(models.Model):
    MALE = "M"
    FEMALE = "F"
    NON_BINARY = "X"

    GENDERS = (
        (MALE, "Male"),
        (FEMALE, "Female"),
        (NON_BINARY, "Non binary"),
    )

    user = models.OneToOneField(ShopUser, null=False, on_delete=models.CASCADE, db_index=True, related_name="profile")
    about = models.TextField(verbose_name="About", max_length=512, blank=True)
    gender = models.CharField(verbose_name="Gender", choices=GENDERS, max_length=1)


@receiver(post_save, sender=ShopUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        ShopUserProfile.objects.create(user=instance)
    else:
        instance.profile.save()

shop/authapp/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    UserChangeForm,
)
from django import forms

from .models import ShopUser, ShopUserProfile
import os
import hashlib


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ("username", "password")

    def __init__(self, *args, **kwargs) -> None:
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = (
            "username",
            "first_name",
            "password1",
            "password2",
            "email",
            "age",
            "city",
            "phone",
            "image",
        )

    def __init__(self, *args, **kwargs):
        super(ShopUserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

    def save(self):
        user = super().save()
        user.is_active = False
        user.activation_key = hashlib.md5(user.email.encode("utf-8") + os.urandom(64)).hexdigest()
        user.save()
        return user


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = (
            "username",
            "first_name",
            "password",
            "email",
            "age",
            "city",
            "phone",
            "image",
        )

    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            if field_name == "password":
                field.widget = forms.HiddenInput()


class ShopUserProfileEditForm(forms.ModelForm):
    class Meta:
        model = ShopUserProfile
        fields = ("about", "gender")

    def __init__(self, *args, **kwargs):
        super(ShopUserProfileEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

shop/authapp/views.py
import pdb
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth
from .forms import (
    ShopUserLoginForm,
    ShopUserRegisterForm,
    ShopUserEditForm,
    ShopUserProfileEditForm,
)
from django.db import transaction

from .utils import send_verify
from .models import ShopUser


def login(request):
    next = request.GET["next"] if "next" in request.GET.keys() else ""

    if request.method == "POST":
        login_form = ShopUserLoginForm(data=request.POST)
        if login_form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]

            user = auth.authenticate(request, username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                if "next" in request.POST.keys():
                    return HttpResponseRedirect(request.POST["next"])
                return HttpResponseRedirect(reverse("index"))
    else:
        login_form = ShopUserLoginForm()

    return render(
        request,
        "authapp/login.html",
        context={
            "title": "Log in",
            "form": login_form,
            "next": next,
        },
    )


def registration(request):
    if request.method == "POST":
        register_form = ShopUserRegisterForm(request.POST, request.FILES)
        if register_form.is_valid():
            user = register_form.save()
            send_verify(user)
            return HttpResponseRedirect(reverse("index"))
    else:
        register_form = ShopUserRegisterForm()

    return render(
        request,
        "authapp/register.html",
        context={
            "title": "Sign in",
            "form": register_form,
        },
    )


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("index"))


@transaction.atomic
def edit(request):
    if request.method == "POST":
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        profile_form = ShopUserProfileEditForm(request.POST, instance=request.user.profile)
        if edit_form.is_valid() and profile_form.is_valid():
            profile_form.save()
            edit_form.save()
            return HttpResponseRedirect(reverse("index"))
    else:
        edit_form = ShopUserEditForm(instance=request.user)
        profile_form = ShopUserProfileEditForm(instance=request.user.profile)

    return render(
        request,
        "authapp/edit.html",
        context={
            "title": "Profile edit",
            "form": edit_form,
            "profile_form": profile_form,
        },
    )


def verify(request, email, activation_key, backend='django.contrib.auth.backends.ModelBackend'):
    user = get_object_or_404(ShopUser, email=email)
    if user.activation_key == activation_key:
        pdb.set_trace()
        user.is_active = True
        user.save()
        auth.login(request, user)
    return render(request, "authapp/verification_complete.html")

shop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    
    {% endblock %}
</head>
<body>
    <div class="container">
        <div class="login">
            <div class="h2 text-center head">
                {{ title }}
            </div>            
            
            {% block content %}
            
            {% endblock %}
        </div>
    </div>
</body>
</html>   

shop/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
{% if user.image %}
<img src="{{ user.image.url }}"/>
{% endif %}
<form method='POST' url="{% url 'auth:edit' %}" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form }}
    {{ profile_form }}
    <input type='submit' value='Save changes' class='submit button'>
</form>
{% endblock content %}

shop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
<form method='POST' url="{% url 'auth:login' %}">
    {% csrf_token %}
    {% if next %}
    <input type="hidden" name="next" value="{{ next }}">
    {% endif %}
    {{ form }}
    <input type='submit' value='Log in' class='submit button'>
    <div class="social_auth_block">
        <img src="{% static 'img/github_social.png' %}" class="social_image">
        <a href="{% url 'social:begin' 'github' %}?next=/" class='submit button social_button'>
            Sign in with GitHub.
        </a>
    </div>
    <div class="social_auth_block">
        <img src="{% static 'img/vk_social.png' %}" class="social_image">
        <a href="{% url 'social:begin' 'vk-oauth2' %}?next=/" class='submit button social_button'>
            Sign in with VK.
        </a>
    </div>
    
</form>
{% endblock content %}

shop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
<form method='POST' url="{% url 'auth:registration' %}">
    {% csrf_token %}
    {{ form }}
    <input type='submit' value='Sign in' class='submit button'>
</form>
{% endblock content %}

shop/authapp/templates/authapp/verification_complete.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}

  {% if user %}
    <h3>Greetings!</h3>
    <br>
    <h4>User {{user.username}} is verified.</h4>
  {% else %}
    <h3>Verification failure</h3>
  {% endif %}
  <br>
  <button class="btn btn-round form-control">
    <a href="{% url 'index' %}" class="">Main</a>
  </button>

{% endblock %}