shop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = "adminapp"

urlpatterns = [
    path("users/create/", adminapp.UserCreateView.as_view(), name="create_user"),
    path("users/read/", adminapp.UserListView.as_view(), name="users"),
    path("users/update/<int:pk>/", adminapp.UserUpdateView.as_view(), name="update_user"),
    path("users/delete/<int:pk>/", adminapp.UserDeleteView.as_view(), name="delete_user"),
    path(
        "categories/create/",
        adminapp.create_category,
        name="create_category",
    ),
    path("categories/read/", adminapp.categories, name="categories"),
    path(
        "categories/update/<int:pk>/",
        adminapp.update_category,
        name="update_category",
    ),
    path(
        "categories/delete/<int:pk>/",
        adminapp.delete_category,
        name="delete_category",
    ),
    path(
        "products/create/category/<int:pk>/",
        adminapp.ProductCreateView.as_view(),
        name="create_product",
    ),
    path("products/read/category/<int:pk>/", adminapp.ProductListView.as_view(), name="products"),
    path("products/read/<int:pk>/", adminapp.ProductView.as_view(), name="read_product"),
    path(
        "products/update/<int:pk>/",
        adminapp.ProductUpdateView.as_view(),
        name="update_product",
    ),
    path(
        "products/delete/<int:pk>/",
        adminapp.delete_product,
        name="delete_product",
    ),
]

shop/authapp/urls.py
from django.urls import path, re_path
from . import views as authapp


app_name = "authapp"

urlpatterns = [
    path("login/", authapp.login, name="login"),
    path("logout/", authapp.logout, name="logout"),
    path("registration/", authapp.registration, name="registration"),
    path("edit/", authapp.edit, name="edit"),
    re_path(r"^verify/(?P<email>.+)/(?P<activation_key>\w+)", authapp.verify, name="verify"),
]

shop/cartapp/urls.py
from django.urls import path
from . import views as cartapp


app_name = "cartapp"

urlpatterns = [
    path("", cartapp.cart_view, name="cart"),
    path("add/<int:product_id>/", cartapp.add_item, name="add"),
    path("remove/<int:cart_item_id>/", cartapp.remove_item, name="remove"),
    path(
        "edit/<int:cart_item_id>/<int:quantity>/",
        cartapp.edit_item,
        name="edit",
    ),
]

shop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp


app_name = "mainapp"

urlpatterns = [
    path("", mainapp.product, name="index"),
    path("<int:pk>/", mainapp.product, name="category"),
    path("<int:pk>/page/<int:page>/", mainapp.product, name="page"),
    path("product/<int:pk>/", mainapp.product_page, name="product"),
]

shop/ordersapp/urls.py
import ordersapp.views as ordersapp
from django.urls import path


app_name = "ordersapp"

urlpatterns = [
    path("", ordersapp.OrderList.as_view(), name="orders_list"),
    path("forming/complete/<int:pk>/", ordersapp.order_forming_complete, name="order_forming_complete"),
    path("create/", ordersapp.OrderCreate.as_view(), name="order_create"),
    path("read/<int:pk>/", ordersapp.OrderDetail.as_view(), name="order_read"),
    path("update/<int:pk>/", ordersapp.OrderUpdate.as_view(), name="order_update"),
    path("delete/<int:pk>/", ordersapp.OrderDelete.as_view(), name="order_delete"),
    path("product/<int:pk>/price/", ordersapp.product_price, name="product_price")
]

shop/shop/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include

from mainapp import views as mainapp


urlpatterns = [
    path("", include("social_django.urls", namespace="social")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("adminapp/", include("adminapp.urls", namespace="custom_admin")),
    path("", mainapp.index, name="index"),
    path("contact/", mainapp.contact, name="contact"),
    path("product/", include("mainapp.urls", namespace="product")),
    path("auth/", include("authapp.urls", namespace="auth")),
    path("cart/", include("cartapp.urls", namespace="cart")),
    path("orders/", include("ordersapp.urls", namespace="orders")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/mainapp/models.py
from functools import cache, lru_cache
from django.db import models
import random


class ProductCategory(models.Model):
    """Model of category for Product model."""

    name = models.CharField(verbose_name="Category name", max_length=100)
    description = models.TextField(
        verbose_name="Category description", blank=True
    )
    is_active = models.BooleanField(verbose_name="Is active", default=True)

    class Meta:
        verbose_name_plural = "Product categories"

    def __str__(self):
        return self.name


class ProductManager(models.Manager):
    @property
    def active_items(self):
        return Product.objects.filter(is_active=True)


class Product(models.Model):
    """Model of shop product."""

    category = models.ForeignKey(
        ProductCategory, on_delete=models.CASCADE, blank=True
    )
    name = models.CharField(verbose_name="Product name", max_length=120)
    price = models.DecimalField(
        verbose_name="Product price", max_digits=6, decimal_places=2, default=0
    )
    color = models.PositiveIntegerField(
        verbose_name="Product color", default=0x000000
    )
    description = models.TextField(
        verbose_name="Product description", blank=True
    )
    image = models.ImageField(
        verbose_name="Product image", blank=True, upload_to="products"
    )
    quantity = models.PositiveIntegerField(
        verbose_name="Product quantity", default=0
    )

    is_active = models.BooleanField(verbose_name="Is active", default=True)

    objects = ProductManager()

    def __str__(self):
        return self.name
    
    @staticmethod
    def random_product(query):
        """Returns random product from pool."""
        return random.choice(query)

shop/mainapp/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.cache import cache
from django.views.decorators.cache import cache_page

from functools import lru_cache

from cartapp.models import Cart
from .models import Product, ProductCategory


@lru_cache
def get_product(category="all"):
    if category == "all":
        return Product.objects.all()[:4]
    return Product.objects.filter(category_id=category)


def get_category(pk=None):
    if settings.LOW_CACHE:
        if pk:
            KEY = f"category_{pk}"
            category = cache.get(KEY)
            if not category:
                category = ProductCategory.objects.filter(pk=pk)
                cache.set(KEY, category)
            return category
        KEY = "all_categories"
        categories = cache.get(KEY)
        if not categories:
            categories = ProductCategory.objects.all()
            cache.set(KEY, categories)
        return categories
    return ProductCategory.objects.filter(pk=pk) if pk else \
            ProductCategory.objects.all()

def index(request):
    """View for main page."""
    product = get_product()
    return render(
        request,
        "mainapp/index.html",
        context={
            "title": "Main",
            "products": product,
        },
    )


def product(request, pk=None, page=1):
    """View for products page."""
    products = get_product(pk) if pk else Product.objects.all()
    hot_product = Product.random_product(products)
    categories = get_category()

    if pk is not None:
        if pk == 0:
            category = {
                "pk": 0,
                "name": "all",
            }
            products = Product.objects.filter(is_active=True)
        else:
            category = get_category(pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True)

    paginator = Paginator(products, 4)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    try:
        content = {
            "title": "Products",
            "products": products_paginator,
            "categories": categories,
            "category": category,
            "hot_product": hot_product,
        }

    except UnboundLocalError:
        content = {
            "title": "Products",
            "products": products_paginator,
            "categories": categories,
            "category": {
                "pk": 0,
                "name": "all",
            },
            "hot_product": hot_product,
        }

    return render(request, "mainapp/products.html", context=content)


def product_page(request, pk):
    """View for specific product."""
    title = "Product page"
    product = get_object_or_404(Product, pk=pk)
    try:
        cart = Cart.get_cart(user=request.user)
    except TypeError:
        return HttpResponseRedirect(reverse("authapp:login"))

    return render(
        request,
        "mainapp/product_page.html",
        context={
            "title": title,
            "product": product,
            "cart": cart,
        },
    )


def category(request, pk):
    """View for page products, used for display specific category of product"""
    categories = get_category()
    category = get_category(pk=pk)
    products = Product.objects.filter(category=category)
    hot_product = Product.random_product(Product.objects.filter(category=category))

    return render(
        request,
        "mainapp/products.html",
        context={
            "title": "Products",
            "products": products,
            "categories": categories,
            "hot_product": hot_product,
        },
    )


def contact(request):
    """View for contacts page."""
    return render(
        request,
        "mainapp/contact.html",
        context={
            "title": "Contacts",
        },
    )

shop/mainapp/templates/mainapp/includes/inc_footer.html
<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB {% now "Y" %}</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
</div>	

shop/mainapp/templates/mainapp/includes/inc_hot_product.html
{% load static %}
<div class="details-products">
    <div class="details-slider">
        <div class="slider-product">
            <img src="{{ hot_product.image.url }}" class="slider_product_main">
        </div>
        <div class="slider-control">
            <div class="block">
                <a href="#"><img src="{{ hot_product.image.url }}" alt="" class="slider_tiny">
                    <div class="text"></div>
                </a>
            </div>
            <div class="block">
                <a href="#"><img src="{{ hot_product.image.url }}" alt="" class="slider_tiny">
                    <div class="text"></div>
                </a>
            </div>
            <div class="block">
                <a href="#"><img src="{{ hot_product.image.url }}" alt="" class="slider_tiny">
                    <div class="text"></div>
                </a>
            </div>
        </div>
    </div>
    
    <div class="description">
        <h3 class="big-bold">{{ hot_product.name }}</h3>
        <h3 class="red">Hot offer</h3>
        <p class="price"> {{ hot_product.price }} <span>руб</span></p>
        <a href="{% url 'cart:add' hot_product.pk %}" class="red-button">
            Add to cart<i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <script type="text/javascript">
        window.onload = function () {
            var quantity = {{ hot_product.quantity }};
            if (quantity - 1 < 0) {
            var buy_button = document.getElementsByClassName("red-button")[0];
            buy_button.style.pointerEvents = "none";
            buy_button.style.opacity = "0.5";
            buy_button.text = "Sorry, out of stock";
            }
        }
  </script>
        <div class="description-text">
            {{ hot_product.description|linebreaks }}
        </div>
    </div>
</div>

shop/mainapp/templates/mainapp/includes/inc_menu.html
<div class="header clearfix">
    <a href="/" class="logo"></a>
    <ul class="menu">
        {% for el in menu %}
        <li><a href={% url el.link %}
            {% if request.resolver_match.view_name in el.active %}
            class="active"
            {% endif %}>
            {{ el.name }}
        </a>
        </li>
        {% endfor %}
    
        {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" id="dropdown">
                    {{ user.username | default:'User' }}
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'auth:edit' %}">
                            Profile
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'ordersapp:orders_list' %}">
                            Orders
                        </a>
                    </li>
                </ul>
            </div>     
        </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
            <a href='{% url "auth:logout" %}'>Log out</a>
            {% else %}
            <a href ='{% url "auth:login" %}'>Log in</a>
            {% endif %}
        </li>
        <li>
            {% if user.is_superuser %}
            <a href="{% url 'adminapp:users' %}">Admin page</a>
            {% endif %}
        </li>
        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'cart:cart' %}" class="basket"></a>
            {% endif %}
        </li>
    </ul>
    
</div>

shop/mainapp/templates/mainapp/includes/inc_related_products.html
{% load static %}
{% for product in products %}
<div class="block">
	<a href="{% url 'product:product' product.id %}">
		{% if product.image %}
		<img src="{{ product.image.url }}"
		{% endif %}
		alt="{{ product.name }}" class="featured_image"> 
		<div class="text">
			<img src="{% static '/img/icon-hover.png' %}" alt="img"/>
			<h4>{{ product.name }}</h4>
			<p>{{ product.description }}</p>
		</div> 
	</a>
</div>
{% endfor %}